language: python

sudo: false

branches:
  only:
    - master
    - develop
env:
  global:
    - LUAROCKS=2.3.0
    - TORCH_SERVER=https://raw.githubusercontent.com/torch/rocks/master/
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks --from=$TORCH_SERVER install dok
  - luarocks --from=$TORCH_SERVER install argcheck
  - luarocks --from=$TORCH_SERVER install torch
  - luarocks --from=$TORCH_SERVER install csvigo
  - luarocks install luafilesystem
  - luarocks install busted
  - luarocks install luacov
  - luarocks make rocks/torch-dataframe-scm-1.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs -ftest-coverage" LIBFLAG="-shared --coverage"

script:
  - git clone git clone https://github.com/geoffleyland/luatrace
  - cd luatrace
  - luarocks make rockspec/luatrace-scm-1.rockspec
  - cd ..
  - lua trace.lua
  - cat trace-out.txt
  - cd specs
  - ./run_all.sh --coverage
  - ./coverage.sh --generate
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
