language: python

sudo: true

branches:
  only:
    - master
    - develop
env:
  global:
    - TORCH_SERVER=https://raw.githubusercontent.com/torch/rocks/master/
  matrix:
    - LUA="LUA51"
    - LUA="LUA52"
    - LUA="LUA53"
    - LUA="LUAJIT20"
    - LUA="LUAJIT21"

before_install:
  - if [[ ! -d torch ]]; then git clone https://github.com/torch/distro.git torch --recursive ; fi
  - cd torch
  - git pull
  - git submodule update
  - git submodule foreach git pull origin master
  - cd ..
  - cp -rf torch torch_$LUA
  - cd torch_$LUA
  - TORCH_LUA_VERSION=$LUA ./install.sh -b
  - cd ..

install:
  - source ./torch_$LUA/install/bin/torch-activate
  - luarocks --from=$TORCH_SERVER install dok
  - luarocks --from=$TORCH_SERVER install argcheck
  - luarocks --from=$TORCH_SERVER install csvigo
  - luarocks install luafilesystem
  - luarocks install busted
  - luarocks install luacov
  - luarocks make rocks/torch-dataframe-scm-1.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs -ftest-coverage" LIBFLAG="-shared --coverage"

script:
  - cd specs
  - ./run_all.sh --coverage
  - ./coverage.sh --generate
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
