language: python

sudo: false

branches:
  only:
    - master
    - travis
    - specs
env:
  global:
    - LUAROCKS=2.3.0
    - TORCH_SERVER=https://raw.githubusercontent.com/torch/rocks/master/
  matrix:
    - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks --from=$TORCH_SERVER install argcheck
  - luarocks --from=$TORCH_SERVER install torch
  - luarocks --from=$TORCH_SERVER install csvigo
  - luarocks install luafilesystem
  - luarocks install busted
  - luarocks make rocks/torch-dataframe-scm-1.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs -ftest-coverage" LIBFLAG="-shared"

script:
  - cd specs
  - ./run_all.sh

after_success:
  - echo "Tests passed"

notifications:
  email:
    on_success: change
    on_failure: always
