language: c

sudo: true

branches:
  only:
    - master
    - travis
env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

before_install:
  - source .travis/setenv_lua.sh
  - travis_wait .travis/install-torch-wrapper.sh $(pwd)/deps/torch $(pwd)/torch-install-log.txt
  - source $(pwd)/deps/torch/install/bin/torch-activate

install:
  - luarocks make torch-dataframe-0.1-1.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs" LIBFLAG="-shared"
  - luarocks install csvigo
  - luarocks install luafilesystem

before_script:
  - source $(pwd)/deps/torch/install/bin/torch-activate

script:
  - cd tests
  - th basic_tests.lua
  - th column_order_tests.lua
  - th categorical_tests.lua
  - th load_batch_tests.lua

after_success:
  - echo "Tests passed"

notifications:
  email:
    on_success: change
    on_failure: always
